# Generated by Django 5.2.17 on 2026-09-30 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('bucket', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('recovery_hash', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('retailer', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='INR', max_length=3)),
                ('bought', models.DateField()),
                ('return_by', models.DateField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('keeping', 'Keeping'), ('returning', 'Return planned'), ('returned', 'Returned')], default='keeping', max_length=12)),
                ('notes', models.TextField(blank=True, max_length=1500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('name', models.CharField(max_length=120)),
                ('content_type', models.CharField(max_length=50)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='tracker.purchase')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['owner', 'return_by'], name='tracker_pur_owner_i_9a345b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['owner', 'warranty_until'], name='tracker_pur_owner_i_78dc7d_idx'),
        ),
    ]
