# Generated by Django 5.2.17 on 2026-09-30 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='purchase_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('return_by__isnull', True), ('return_by__gte', models.F('bought')), _connector='OR'), name='purchase_return_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('warranty_until__isnull', True), ('warranty_until__gte', models.F('bought')), _connector='OR'), name='purchase_warranty_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['INR', 'USD', 'EUR', 'GBP'])), name='purchase_currency_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['keeping', 'returning', 'returned'])), name='purchase_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('data__length__lte', 2097152)), name='receipt_size_bounded'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ['image/jpeg', 'application/pdf'])), name='receipt_type_valid'),
        ),
    ]
